//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltKategoriler
    {
        public int AltKategoriId { get; set; }
        public string AltKategoriAdi { get; set; }
        public string Ikon { get; set; }
        public string Slug { get; set; }
        public string Url { get; set; }
        public bool Aktif { get; set; }
        public bool Area { get; set; }
        public bool Depart { get; set; }
        public int KategoriId { get; set; }
        public int Sira { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
