//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketler
    {
        public int AnketId { get; set; }
        public string ip { get; set; }
        public Nullable<int> KurumId { get; set; }
        public string OgrencininAdi { get; set; }
        public string OgrencininSinifi { get; set; }
        public Nullable<int> EnSevdiginizOgretmenveBransi { get; set; }
        public string EnSevdiginizOgretmenvNedeni { get; set; }
        public Nullable<int> EnSevdiginizYonetici { get; set; }
        public string EnSevdiginizYoneticiNedeni { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> Ay { get; set; }
    }
}
