//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DosyaYoneticisi
    {
        public int DosyaId { get; set; }
        public string DosyaAdi { get; set; }
        public string Url { get; set; }
        public string Ikon { get; set; }
        public string Boyut { get; set; }
        public string Uzanti { get; set; }
        public System.DateTime Tarih { get; set; }
    }
}
