//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haberler()
        {
            this.HaberlerResim = new HashSet<HaberlerResim>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Resim { get; set; }
        public string Slug { get; set; }
        public string Detay { get; set; }
        public bool Aktif { get; set; }
        public int KategoriId { get; set; }
        public Nullable<int> GaleriId { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Hit { get; set; }
    
        public virtual Galeri Galeri { get; set; }
        public virtual HaberKategorileri HaberKategorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaberlerResim> HaberlerResim { get; set; }
    }
}
