//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int Id { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string Mail { get; set; }
        public string Harita { get; set; }
        public string Adres { get; set; }
        public string Mailler { get; set; }
        public string DestekMailler { get; set; }
        public int SmtpPort { get; set; }
        public string SmtpMail { get; set; }
        public string SmtpAdres { get; set; }
        public string Sifre { get; set; }
    }
}
