//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurumlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurumlar()
        {
            this.KurumResim = new HashSet<KurumResim>();
            this.KurumEgitimciler = new HashSet<KurumEgitimciler>();
        }
    
        public int KurumId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> AltKategoriId { get; set; }
        public Nullable<int> ilId { get; set; }
        public Nullable<int> ilceId { get; set; }
        public string KurumAdi { get; set; }
        public string Slug { get; set; }
        public string UploadYolu { get; set; }
        public string Resim { get; set; }
        public string KurumMuduru { get; set; }
        public string MudurYardimcilari { get; set; }
        public string Aktiviteler { get; set; }
        public string Aciklama { get; set; }
        public string KurulusTarih { get; set; }
        public string WebSitesi { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Harita { get; set; }
        public string Video { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public bool Durum { get; set; }
        public string Subeler { get; set; }
        public string Kurucusu { get; set; }
        public string Egitimciler { get; set; }
        public string Panoroma { get; set; }
    
        public virtual AltKategoriler AltKategoriler { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KurumResim> KurumResim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KurumEgitimciler> KurumEgitimciler { get; set; }
    }
}
