//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markalar
    {
        public int MarkaId { get; set; }
        public string MarkaAdi { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
        public string Slug { get; set; }
        public bool Aktif { get; set; }
        public bool Area { get; set; }
        public bool Depart { get; set; }
        public Nullable<int> Sira { get; set; }
    }
}
