//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminler> Adminler { get; set; }
        public virtual DbSet<AdminRolIliski> AdminRolIliski { get; set; }
        public virtual DbSet<AdminRolleri> AdminRolleri { get; set; }
        public virtual DbSet<AltKategoriler> AltKategoriler { get; set; }
        public virtual DbSet<Bulten> Bulten { get; set; }
        public virtual DbSet<Cozumler> Cozumler { get; set; }
        public virtual DbSet<DosyaYoneticisi> DosyaYoneticisi { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<Galeri> Galeri { get; set; }
        public virtual DbSet<GaleriResim> GaleriResim { get; set; }
        public virtual DbSet<HaberKategorileri> HaberKategorileri { get; set; }
        public virtual DbSet<Haberler> Haberler { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<MetaTag> MetaTag { get; set; }
        public virtual DbSet<Popup> Popup { get; set; }
        public virtual DbSet<Sayfalar> Sayfalar { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Kurumlar> Kurumlar { get; set; }
        public virtual DbSet<SliderKategori> SliderKategori { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Reklamlar> Reklamlar { get; set; }
    }
}
