//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamlar
    {
        public int Id { get; set; }
        public string KategorKodu { get; set; }
        public string Url { get; set; }
        public string Target { get; set; }
        public string Resim { get; set; }
    }
}
