//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int Id { get; set; }
        public int SliderId { get; set; }
        public string Baslik { get; set; }
        public string Url { get; set; }
        public string Target { get; set; }
        public string Resim { get; set; }
        public int Sira { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual SliderKategori SliderKategori { get; set; }
    }
}
