//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobit.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Anketler
    {
        public int AnketId { get; set; }
        public string ip { get; set; }
        public Nullable<int> KurumId { get; set; }
        public string OgrencininAdi { get; set; }
        public string OgrencininSinifi { get; set; }
        public Nullable<int> EnSevdiginizOgretmenveBransi { get; set; }
        public string EnSevdiginizOgretmenvNedeni { get; set; }
        public Nullable<int> EnSevdiginizYonetici { get; set; }
        public string EnSevdiginizYoneticiNedeni { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> Ay { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> AltKategoriId { get; set; }
        public Nullable<int> ilId { get; set; }
        public Nullable<int> ilceId { get; set; }
        public string KurumAdi { get; set; }
        public string UploadYolu { get; set; }
        public string Resim { get; set; }
        public string KurumMuduru { get; set; }
        public string MudurYardimcilari { get; set; }
        public string Aktiviteler { get; set; }
        public string Aciklama { get; set; }
        public string KurulusTarih { get; set; }
        public string WebSitesi { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Harita { get; set; }
        public string Video { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Subeler { get; set; }
        public string Kurucusu { get; set; }
        public string Egitimciler { get; set; }
        public string Panoroma { get; set; }
        public string EnSevdiginizEgitimciAdiSoyadi { get; set; }
        public string EnSevdiginizYoneticiAdiSoyadi { get; set; }
        public string EnSevdiginizEgitimciAdiSoyadiResim { get; set; }
        public string EnSevdiginizYoneticiAdiSoyadiResim { get; set; }
    }
}
